# Generated by Django 3.2 on 2023-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Укажите название произведения', max_length=256, verbose_name='Название произведения'),
        ),
    ]
